### PR TITLE
RV32 version

### PR DESCRIPTION
**Pull request by drom**
I have only RV32 on my test bench. So I have made some minor fixes to support RV32.

### CODE REVIEW

**Comment by tommythorn** [comment]
Thanks that's right but not complete.  However until I say otherwise, better use the simple branch is should be 100% reliable.

**Comment by tommythorn** [comment]
https://github.com/tommythorn/coroutines_for_C/tree/simple

**Comment by tommythorn** [comment]
Ok, let me pull your change and swap things around.  One sec.

**Comment by drom** [comment]
I can test on LLVM + RV32
https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf

**Comment by tommythorn** [comment]
Ok, I pushed an untested (not even compiled) change that may work.

**Pull request closed without merging**
